name = "strict_email_validator"
description = ""
version = "1.0.1"

authors = ["Vladimir Fedorov"]
maintainers = ["Vladimir Fedorov <khv2online@gmail.com>"]
maintainers-logins = ["khv2online"]
licenses = "MIT"
website = "https://github.com/yasusoft-official/strict_email_validator"
tags = ["email"]

[build-switches]
"*".ada_version = "Ada12"
development.style_checks = "No"
