name = "strict_email_validator"
description = ""
version = "0.1.0-dev"

authors = ["Vladimir Fedorov"]
maintainers = ["Vladimir Fedorov <khv2online@gmail.com>"]
maintainers-logins = ["khv2online"]
licenses = "MIT"
website = ""
tags = []

[build-switches]
"*".ada_version = "Ada12"
development.style_checks = "No"
